### ISSUE TITLE
Training Data Format

### ISSUE THREAD

**Issue by Sean-Bin-Yang** [boathit/deepgtt#2]
Hi Xiucheng,

Thanks for great work. There is one thing i want to ask is that if i want to skip the map matching step and use my own dataset. Could you please give me some suggestion about the training /testing /validation data format. Thanks.

Kind regards,

Sean

**Comment by boathit** [comment]
Hi Yang Bin,

You can simply skip the map matching step and start from [generate training data](https://github.com/boathit/deepgtt#generate-training-validation-and-test-data), in which case you are supposed to put your data into the `jldpath` folder with the name `gps_yyyymmdd.jld2`, e.g., `gps_20161101.jld2` which holds the trips collected during Nov 01, 2016, the trips are organized by day as julia [jld2](https://github.com/JuliaIO/JLD2.jl) files.

The code loading the jld2 files into memory is in [this line](https://github.com/boathit/deepgtt/blob/master/harbin/julia/traindata.jl#L53). In short, each jld2 file holds a collection of trip data defined [here](https://github.com/boathit/deepgtt/blob/master/harbin/julia/Trip.jl#L7) like,

```julia
mutable struct Trip{T<:AbstractFloat}
    lon::Vector{T}
    lat::Vector{T}
    tms::Vector{T}
    devid
    roads
end
```

which means you are supposed to dump your one day data as a collection `Trip`, i,e., `Vector{Trip}` and save it as a jld2 file. Since you have your own matched road segments, you can initialize a `Trip` with a new constructed function (put it below [this line](https://github.com/boathit/deepgtt/blob/master/harbin/julia/Trip.jl#L16))

```julia
Trip(lon, lat, tms, roads) = Trip(lon, lat, tms, 0, roads)
```

where `lon`, `lat` are vectors of longitude and latitude, respectively, `tms` is a vector of unix timestamp and `roads` is a vector of road segment ids.

**Comment by Sean-Bin-Yang** [comment]
Hi Xiucheng,

Thank you very much.
